package ua.bossly.tools.translit.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Tokens
val md_theme_light_primary = Color(0xFFB91D34)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDAD9)
val md_theme_light_onPrimaryContainer = Color(0xFF41000A)
val md_theme_light_secondary = Color(0xFF775656)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDAD9)
val md_theme_light_onSecondaryContainer = Color(0xFF2C1516)
val md_theme_light_tertiary = Color(0xFF755A2F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDAE)
val md_theme_light_onTertiaryContainer = Color(0xFF2A1800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF8F7)
val md_theme_light_onBackground = Color(0xFF221919)
val md_theme_light_surface = Color(0xFFFFF8F7)
val md_theme_light_onSurface = Color(0xFF221919)
val md_theme_light_surfaceVariant = Color(0xFFF4DDDD)
val md_theme_light_onSurfaceVariant = Color(0xFF524343)
val md_theme_light_outline = Color(0xFF857373)
val md_theme_light_outlineVariant = Color(0xFFD7C1C1)

// Dark Theme Tokens
val md_theme_dark_primary = Color(0xFFFFB3B4)
val md_theme_dark_onPrimary = Color(0xFF680016)
val md_theme_dark_primaryContainer = Color(0xFF920023)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_secondary = Color(0xFFE6BDBC)
val md_theme_dark_onSecondary = Color(0xFF44292A)
val md_theme_dark_secondaryContainer = Color(0xFF5D3F40)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD9)
val md_theme_dark_tertiary = Color(0xFFE5C18D)
val md_theme_dark_onTertiary = Color(0xFF422C05)
val md_theme_dark_tertiaryContainer = Color(0xFF5B421A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDAE)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1111)
val md_theme_dark_onBackground = Color(0xFFF0DEDE)
val md_theme_dark_surface = Color(0xFF1A1111)
val md_theme_dark_onSurface = Color(0xFFF0DEDE)
val md_theme_dark_surfaceVariant = Color(0xFF524343)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C1C1)
val md_theme_dark_outline = Color(0xFFA08C8C)
val md_theme_dark_outlineVariant = Color(0xFF524343)