name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: release.keystore
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Create keystore.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > keystore.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> keystore.properties

      - name: Publish to Google Play
        uses: maierj/fastlane-action@v1.4.0
        env:
          APP_BUILD_NUMBER: ${{ github.GITHUB_RUN_ID }}
          APP_VERSION_CODE: ${{ github.ref }}
          SUPPLY_JSON_KEY_DATA: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        with:
          lane: deploy
          skip-tracking: false
          subdirectory: fastlane
          bundle-install-path: CACHE_BUNDLER